/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * API keys model
 * @export
 * @interface ApiKeyResponse
 */
export interface ApiKeyResponse {
    /**
     * Unique identifier of the API key
     * @type {string}
     * @memberof ApiKeyResponse
     */
    'id': string;
    /**
     * Object name, value is \'api_key\'
     * @type {string}
     * @memberof ApiKeyResponse
     */
    'object': ApiKeyResponseObjectEnum;
    /**
     * Indicates if the API key is active
     * @type {boolean}
     * @memberof ApiKeyResponse
     */
    'active': boolean;
    /**
     * Indicates if the API key is in production
     * @type {boolean}
     * @memberof ApiKeyResponse
     */
    'livemode': boolean;
    /**
     * Indicates if the API key is private or public
     * @type {string}
     * @memberof ApiKeyResponse
     */
    'role': ApiKeyResponseRoleEnum;
    /**
     * A name or brief explanation of what this API key is used for
     * @type {string}
     * @memberof ApiKeyResponse
     */
    'description'?: string | null;
    /**
     * The first few characters of the authentication_token
     * @type {string}
     * @memberof ApiKeyResponse
     */
    'prefix': string;
    /**
     * Unix timestamp in seconds of when the API key was created
     * @type {number}
     * @memberof ApiKeyResponse
     */
    'created_at': number;
    /**
     * Unix timestamp in seconds of when the API key was last updated
     * @type {number}
     * @memberof ApiKeyResponse
     */
    'updated_at': number;
    /**
     * Unix timestamp in seconds of when the API key was deactivated
     * @type {number}
     * @memberof ApiKeyResponse
     */
    'deactivated_at'?: number | null;
    /**
     * Indicates if the API key was deleted
     * @type {boolean}
     * @memberof ApiKeyResponse
     */
    'deleted'?: boolean;
}

export const ApiKeyResponseObjectEnum = {
    apiKey: 'api_key'
} as const;

export type ApiKeyResponseObjectEnum = typeof ApiKeyResponseObjectEnum[keyof typeof ApiKeyResponseObjectEnum];
export const ApiKeyResponseRoleEnum = {
    private: 'private',
    public: 'public'
} as const;

export type ApiKeyResponseRoleEnum = typeof ApiKeyResponseRoleEnum[keyof typeof ApiKeyResponseRoleEnum];


