/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiKeyUpdateRequest
 */
export interface ApiKeyUpdateRequest {
    /**
     * Indicates whether the API key is active.
     * @type {boolean}
     * @memberof ApiKeyUpdateRequest
     */
    'active'?: boolean;
    /**
     * A name or brief explanation of what this API key is used for.
     * @type {string}
     * @memberof ApiKeyUpdateRequest
     */
    'description'?: string;
}

