/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiKeyRequest
 */
export interface ApiKeyRequest {
    /**
     * A name or brief explanation of what this API key is used for.
     * @type {string}
     * @memberof ApiKeyRequest
     */
    'description'?: string;
    /**
     * Defines the type of API key to create. Only \"private\" is supported for creation. A \"public\" API key already exists by default per company/environment. 
     * @type {string}
     * @memberof ApiKeyRequest
     */
    'role': ApiKeyRequestRoleEnum;
}

export const ApiKeyRequestRoleEnum = {
    private: 'private'
} as const;

export type ApiKeyRequestRoleEnum = typeof ApiKeyRequestRoleEnum[keyof typeof ApiKeyRequestRoleEnum];


