/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BalanceCommonField } from './balance-common-field';

/**
 * Company balance summary.  Monetary fields are returned as arrays of amounts grouped by currency (see `balance_common_field` items). 
 * @export
 * @interface BalanceResponse
 */
export interface BalanceResponse {
    /**
     * Amounts currently available, grouped by currency.
     * @type {Array<BalanceCommonField>}
     * @memberof BalanceResponse
     */
    'available': Array<BalanceCommonField>;
    /**
     * Amounts pending settlement, grouped by currency.
     * @type {Array<BalanceCommonField>}
     * @memberof BalanceResponse
     */
    'pending': Array<BalanceCommonField>;
    /**
     * Retention amount applied, grouped by currency.
     * @type {Array<BalanceCommonField>}
     * @memberof BalanceResponse
     */
    'retention_amount': Array<BalanceCommonField>;
    /**
     * Amounts currently retained, grouped by currency.
     * @type {Array<BalanceCommonField>}
     * @memberof BalanceResponse
     */
    'retained': Array<BalanceCommonField>;
    /**
     * Amounts temporarily retained, grouped by currency.
     * @type {Array<BalanceCommonField>}
     * @memberof BalanceResponse
     */
    'temporarily_retained': Array<BalanceCommonField>;
    /**
     * Target retention amount, grouped by currency.
     * @type {Array<BalanceCommonField>}
     * @memberof BalanceResponse
     */
    'target_retention_amount': Array<BalanceCommonField>;
    /**
     * Target temporary retention amount, grouped by currency.
     * @type {Array<BalanceCommonField>}
     * @memberof BalanceResponse
     */
    'target_temporary_retention_amount': Array<BalanceCommonField>;
    /**
     * Target collateral amount, grouped by currency.
     * @type {Array<BalanceCommonField>}
     * @memberof BalanceResponse
     */
    'target_collateral_amount': Array<BalanceCommonField>;
    /**
     * Gateway balance amounts, grouped by currency.
     * @type {Array<BalanceCommonField>}
     * @memberof BalanceResponse
     */
    'gateway': Array<BalanceCommonField>;
    /**
     * Cashout retention debited amounts, grouped by currency.
     * @type {Array<BalanceCommonField>}
     * @memberof BalanceResponse
     */
    'cashout_retention_debited': Array<BalanceCommonField>;
}

