/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request body to update a charge. Only `reference_id` can be updated.
 * @export
 * @interface ChargeUpdateRequest
 */
export interface ChargeUpdateRequest {
    /**
     * custom reference id
     * @type {string}
     * @memberof ChargeUpdateRequest
     */
    'reference_id'?: string;
}

