/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Payment method used in the charge. 
 * @export
 * @interface ChargeRequestPaymentMethod
 */
export interface ChargeRequestPaymentMethod {
    /**
     * Method expiration date as unix timestamp (applies to some payment methods, e.g. cash).
     * @type {number}
     * @memberof ChargeRequestPaymentMethod
     */
    'expires_at'?: number;
    /**
     * 
     * @type {string}
     * @memberof ChargeRequestPaymentMethod
     */
    'type': string;
    /**
     * Identifier of a saved payment source to be used for this charge (if applicable).
     * @type {string}
     * @memberof ChargeRequestPaymentMethod
     */
    'payment_source_id'?: string;
}

