/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Payment method used in the charge. 
 * @export
 * @interface ChargeRequestPaymentMethod
 */
export interface ChargeRequestPaymentMethod {
    /**
     * Payment method type.
     * @type {string}
     * @memberof ChargeRequestPaymentMethod
     */
    'type': ChargeRequestPaymentMethodTypeEnum;
    /**
     * Method expiration date as unix timestamp (applies to some payment methods, e.g. cash).
     * @type {number}
     * @memberof ChargeRequestPaymentMethod
     */
    'expires_at'?: number | null;
    /**
     * Identifier of a saved payment source to be used for this charge (if applicable).
     * @type {string}
     * @memberof ChargeRequestPaymentMethod
     */
    'payment_source_id'?: string | null;
}

export const ChargeRequestPaymentMethodTypeEnum = {
    cash: 'cash',
    oxxoCash: 'oxxo_cash'
} as const;

export type ChargeRequestPaymentMethodTypeEnum = typeof ChargeRequestPaymentMethodTypeEnum[keyof typeof ChargeRequestPaymentMethodTypeEnum];


