/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CheckoutOrderTemplateCustomerInfo } from './checkout-order-template-customer-info';
// May contain unused imports in some cases
// @ts-ignore
import { Product } from './product';

/**
 * Attributes used to create the order when a new payment is received.
 * @export
 * @interface CheckoutOrderTemplate
 */
export interface CheckoutOrderTemplate {
    /**
     * ISO 4217 currency code for the order.
     * @type {string}
     * @memberof CheckoutOrderTemplate
     */
    'currency': string;
    /**
     * 
     * @type {CheckoutOrderTemplateCustomerInfo}
     * @memberof CheckoutOrderTemplate
     */
    'customer_info'?: CheckoutOrderTemplateCustomerInfo;
    /**
     * Products to buy. Each contains unit price and quantity used to calculate the order total.
     * @type {Array<Product>}
     * @memberof CheckoutOrderTemplate
     */
    'line_items': Array<Product>;
    /**
     * Arbitrary key-value data attached to the order for internal use.
     * @type {{ [key: string]: any; }}
     * @memberof CheckoutOrderTemplate
     */
    'metadata'?: { [key: string]: any; };
}

