/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * checkout response
 * @export
 * @interface CheckoutResponse
 */
export interface CheckoutResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof CheckoutResponse
     */
    'allowed_payment_methods'?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof CheckoutResponse
     */
    'can_not_expire'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CheckoutResponse
     */
    'emails_sent'?: number;
    /**
     * 
     * @type {number}
     * @memberof CheckoutResponse
     */
    'expires_at'?: number;
    /**
     * 
     * @type {string}
     * @memberof CheckoutResponse
     */
    'failure_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutResponse
     */
    'id': string;
    /**
     * 
     * @type {boolean}
     * @memberof CheckoutResponse
     */
    'livemode': boolean;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CheckoutResponse
     */
    'metadata'?: { [key: string]: any; };
    /**
     * Payment link name
     * @type {string}
     * @memberof CheckoutResponse
     */
    'name': string;
    /**
     * 
     * @type {boolean}
     * @memberof CheckoutResponse
     */
    'needs_shipping_contact'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CheckoutResponse
     */
    'object': string;
    /**
     * 
     * @type {number}
     * @memberof CheckoutResponse
     */
    'paid_payments_count'?: number;
    /**
     * 
     * @type {number}
     * @memberof CheckoutResponse
     */
    'payments_limit_count'?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof CheckoutResponse
     */
    'recurrent'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CheckoutResponse
     */
    'slug'?: string;
    /**
     * 
     * @type {number}
     * @memberof CheckoutResponse
     */
    'sms_sent'?: number;
    /**
     * 
     * @type {number}
     * @memberof CheckoutResponse
     */
    'starts_at'?: number;
    /**
     * 
     * @type {string}
     * @memberof CheckoutResponse
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutResponse
     */
    'success_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutResponse
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutResponse
     */
    'url'?: string;
}

