/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CheckoutOrderTemplate } from './checkout-order-template';

/**
 * Creates a Payment Link. This is a sub-resource related to an Order template: each time a customer pays using the link, the API will create an Order using `order_template`. 
 * @export
 * @interface Checkout
 */
export interface Checkout {
    /**
     * Payment link name.
     * @type {string}
     * @memberof Checkout
     */
    'name': string;
    /**
     * Checkout type.
     * @type {string}
     * @memberof Checkout
     */
    'type': string;
    /**
     * false: single use. true: multiple payments
     * @type {boolean}
     * @memberof Checkout
     */
    'recurrent': boolean;
    /**
     * Required when `recurrent` is true. Maximum number of payments allowed through the link.
     * @type {number}
     * @memberof Checkout
     */
    'payments_limit_count'?: number;
    /**
     * Payment methods available in the payment link.
     * @type {Array<string>}
     * @memberof Checkout
     */
    'allowed_payment_methods': Array<string>;
    /**
     * This flag allows you to fill in the shipping information at checkout.
     * @type {boolean}
     * @memberof Checkout
     */
    'needs_shipping_contact': boolean;
    /**
     * Start time for the link. Unix timestamp in seconds.
     * @type {number}
     * @memberof Checkout
     */
    'starts_at'?: number;
    /**
     * Expiration time for the link (Unix timestamp in seconds). Valid range is between 2 and 365 days (calculated from the next day of creation at 00:01). 
     * @type {number}
     * @memberof Checkout
     */
    'expires_at': number;
    /**
     * If true, the link does not expire.
     * @type {boolean}
     * @memberof Checkout
     */
    'can_not_expire'?: boolean;
    /**
     * 
     * @type {CheckoutOrderTemplate}
     * @memberof Checkout
     */
    'order_template': CheckoutOrderTemplate;
}

