/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PaymentMethodCashRequest } from './payment-method-cash-request';

/**
 * @type CreateCustomerPaymentMethodsRequest
 * Contains details of the payment methods that the customer has active or has used in Femsa
 * @export
 */
export type CreateCustomerPaymentMethodsRequest = PaymentMethodCashRequest;


