/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Payment method data to attach to a customer.
 * @export
 * @interface CustomerPaymentMethodRequest
 */
export interface CustomerPaymentMethodRequest {
    /**
     * Type of payment method.
     * @type {string}
     * @memberof CustomerPaymentMethodRequest
     */
    'type': string;
}

