/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CustomerFiscalEntitiesResponse } from './customer-fiscal-entities-response';
// May contain unused imports in some cases
// @ts-ignore
import { CustomerPaymentMethodsResponse } from './customer-payment-methods-response';
// May contain unused imports in some cases
// @ts-ignore
import { CustomerResponseShippingContacts } from './customer-response-shipping-contacts';

/**
 * customer response
 * @export
 * @interface CustomerResponse
 */
export interface CustomerResponse {
    /**
     * Customer\'s ID
     * @type {string}
     * @memberof CustomerResponse
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof CustomerResponse
     */
    'object': CustomerResponseObjectEnum;
    /**
     * Creation date of the object (Unix timestamp)
     * @type {number}
     * @memberof CustomerResponse
     */
    'created_at': number;
    /**
     * true if the object exists in live mode or false if the object exists in test mode
     * @type {boolean}
     * @memberof CustomerResponse
     */
    'livemode': boolean;
    /**
     * Customer\'s name
     * @type {string}
     * @memberof CustomerResponse
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerResponse
     */
    'email'?: string | null;
    /**
     * Customer\'s phone number
     * @type {string}
     * @memberof CustomerResponse
     */
    'phone'?: string | null;
    /**
     * true if the customer is a company
     * @type {boolean}
     * @memberof CustomerResponse
     */
    'corporate'?: boolean;
    /**
     * Custom reference
     * @type {string}
     * @memberof CustomerResponse
     */
    'custom_reference'?: string | null;
    /**
     * Referrer information (if available)
     * @type {string}
     * @memberof CustomerResponse
     */
    'referrer'?: string | null;
    /**
     * Vertical-specific information (shape depends on integration)
     * @type {{ [key: string]: any; }}
     * @memberof CustomerResponse
     */
    'vertical_info'?: { [key: string]: any; } | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerResponse
     */
    'default_fiscal_entity_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerResponse
     */
    'default_shipping_contact_id'?: string | null;
    /**
     * Customer metadata (maps to contextual_data in backend)
     * @type {{ [key: string]: any; }}
     * @memberof CustomerResponse
     */
    'metadata'?: { [key: string]: any; } | null;
    /**
     * 
     * @type {CustomerPaymentMethodsResponse}
     * @memberof CustomerResponse
     */
    'payment_sources'?: CustomerPaymentMethodsResponse;
    /**
     * 
     * @type {CustomerFiscalEntitiesResponse}
     * @memberof CustomerResponse
     */
    'fiscal_entities'?: CustomerFiscalEntitiesResponse;
    /**
     * 
     * @type {CustomerResponseShippingContacts}
     * @memberof CustomerResponse
     */
    'shipping_contacts'?: CustomerResponseShippingContacts;
}

export const CustomerResponseObjectEnum = {
    customer: 'customer'
} as const;

export type CustomerResponseObjectEnum = typeof CustomerResponseObjectEnum[keyof typeof CustomerResponseObjectEnum];


