/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CustomerFiscalEntitiesRequest } from './customer-fiscal-entities-request';
// May contain unused imports in some cases
// @ts-ignore
import { CustomerPaymentSourcesInner } from './customer-payment-sources-inner';
// May contain unused imports in some cases
// @ts-ignore
import { CustomerShippingContacts } from './customer-shipping-contacts';

/**
 * Customer create request.
 * @export
 * @interface Customer
 */
export interface Customer {
    /**
     * Customer\'s name.
     * @type {string}
     * @memberof Customer
     */
    'name': string;
    /**
     * Customer email address.
     * @type {string}
     * @memberof Customer
     */
    'email': string;
    /**
     * Customer phone number.
     * @type {string}
     * @memberof Customer
     */
    'phone'?: string | null;
    /**
     * Indicates whether the customer email is corporate.
     * @type {boolean}
     * @memberof Customer
     */
    'corporate'?: boolean;
    /**
     * Merchant-defined reference used to identify the customer in your system.
     * @type {string}
     * @memberof Customer
     */
    'custom_reference'?: string | null;
    /**
     * Referrer value (if applicable).
     * @type {string}
     * @memberof Customer
     */
    'referrer'?: string | null;
    /**
     * Arbitrary metadata associated with the customer.
     * @type {{ [key: string]: any; }}
     * @memberof Customer
     */
    'metadata'?: { [key: string]: any; };
    /**
     * Customer fiscal entities to be created with the customer (optional).
     * @type {Array<CustomerFiscalEntitiesRequest>}
     * @memberof Customer
     */
    'fiscal_entities'?: Array<CustomerFiscalEntitiesRequest> | null;
    /**
     * Customer shipping contacts to be created with the customer (optional).
     * @type {Array<CustomerShippingContacts>}
     * @memberof Customer
     */
    'shipping_contacts'?: Array<CustomerShippingContacts> | null;
    /**
     * Customer payment sources to be created with the customer (optional).
     * @type {Array<CustomerPaymentSourcesInner>}
     * @memberof Customer
     */
    'payment_sources'?: Array<CustomerPaymentSourcesInner> | null;
}

