/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CustomerShippingContactsAddress } from './customer-shipping-contacts-address';

/**
 * [Shipping Contacts](https://developers.femsa.com/v2.2.0/reference/createcustomershippingcontacts) details for updating a customer shipping contact. Only the fields provided in the request body are updated.
 * @export
 * @interface CustomerUpdateShippingContacts
 */
export interface CustomerUpdateShippingContacts {
    /**
     * Phone contact
     * @type {string}
     * @memberof CustomerUpdateShippingContacts
     */
    'phone'?: string;
    /**
     * Name of the person who will receive the order
     * @type {string}
     * @memberof CustomerUpdateShippingContacts
     */
    'receiver'?: string;
    /**
     * The street names between which the order will be delivered.
     * @type {string}
     * @memberof CustomerUpdateShippingContacts
     */
    'between_streets'?: string;
    /**
     * 
     * @type {CustomerShippingContactsAddress}
     * @memberof CustomerUpdateShippingContacts
     */
    'address'?: CustomerShippingContactsAddress;
    /**
     * Metadata associated with the shipping contact
     * @type {{ [key: string]: any; }}
     * @memberof CustomerUpdateShippingContacts
     */
    'metadata'?: { [key: string]: any; };
}

