/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CustomerAddress } from './customer-address';

/**
 * 
 * @export
 * @interface CustomerUpdateFiscalEntitiesRequest
 */
export interface CustomerUpdateFiscalEntitiesRequest {
    /**
     * 
     * @type {CustomerAddress}
     * @memberof CustomerUpdateFiscalEntitiesRequest
     */
    'address'?: CustomerAddress;
    /**
     * 
     * @type {string}
     * @memberof CustomerUpdateFiscalEntitiesRequest
     */
    'tax_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerUpdateFiscalEntitiesRequest
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerUpdateFiscalEntitiesRequest
     */
    'phone'?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CustomerUpdateFiscalEntitiesRequest
     */
    'metadata'?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof CustomerUpdateFiscalEntitiesRequest
     */
    'company_name'?: string;
}

