/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import {
  CustomerShippingContactsResponseAddress
} from './customer-shipping-contacts-response-address';

/**
 * Contains the detail of the shipping addresses that the client has active or has used in Femsa
 * @export
 * @interface CustomerShippingContactsResponse
 */
export interface CustomerShippingContactsResponse {
    /**
     * 
     * @type {string}
     * @memberof CustomerShippingContactsResponse
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerShippingContactsResponse
     */
    'receiver'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerShippingContactsResponse
     */
    'between_streets'?: string | null;
    /**
     * 
     * @type {CustomerShippingContactsResponseAddress}
     * @memberof CustomerShippingContactsResponse
     */
    'address'?: CustomerShippingContactsResponseAddress;
    /**
     * Customer ID that owns this shipping contact.
     * @type {string}
     * @memberof CustomerShippingContactsResponse
     */
    'parent_id'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CustomerShippingContactsResponse
     */
    'default'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CustomerShippingContactsResponse
     */
    'id'?: string;
    /**
     * 
     * @type {number}
     * @memberof CustomerShippingContactsResponse
     */
    'created_at'?: number;
    /**
     * Metadata associated with the shipping contact
     * @type {{ [key: string]: any; }}
     * @memberof CustomerShippingContactsResponse
     */
    'metadata'?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof CustomerShippingContactsResponse
     */
    'object'?: string;
    /**
     * Present only when the shipping contact was deleted.
     * @type {boolean}
     * @memberof CustomerShippingContactsResponse
     */
    'deleted'?: boolean;
}

