/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import {PaymentMethodCashResponse} from './payment-method-cash-response';

/**
 * @type CustomerPaymentMethodsData
 * @export
 */
export type CustomerPaymentMethodsData = { type: 'cash' } & PaymentMethodCashResponse | { type: 'oxxo_recurrent' } & PaymentMethodCashResponse;


