/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Log model representing a recorded request/response cycle for troubleshooting and auditing.
 * @export
 * @interface LogResponse
 */
export interface LogResponse {
    /**
     * 
     * @type {string}
     * @memberof LogResponse
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof LogResponse
     */
    'object': LogResponseObjectEnum;
    /**
     * 
     * @type {number}
     * @memberof LogResponse
     */
    'created_at': number;
    /**
     * 
     * @type {string}
     * @memberof LogResponse
     */
    'updated_at'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof LogResponse
     */
    'livemode': boolean;
    /**
     * 
     * @type {string}
     * @memberof LogResponse
     */
    'ip_address'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogResponse
     */
    'loggable_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LogResponse
     */
    'loggable_type'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LogResponse
     */
    'method'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogResponse
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogResponse
     */
    'related'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogResponse
     */
    'version'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogResponse
     */
    'user_account_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LogResponse
     */
    'oauth_token_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LogResponse
     */
    'status'?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof LogResponse
     */
    'query_string'?: { [key: string]: any; } | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof LogResponse
     */
    'request_headers'?: { [key: string]: string; } | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof LogResponse
     */
    'response_headers'?: { [key: string]: string; } | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof LogResponse
     */
    'request_body'?: { [key: string]: any; } | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof LogResponse
     */
    'response_body'?: { [key: string]: any; } | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof LogResponse
     */
    'searchable_tags'?: Array<string>;
}

export const LogResponseObjectEnum = {
    log: 'log'
} as const;

export type LogResponseObjectEnum = typeof LogResponseObjectEnum[keyof typeof LogResponseObjectEnum];


