/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Log model representing a recorded request/response cycle for troubleshooting and auditing.
 * @export
 * @interface LogsResponse
 */
export interface LogsResponse {
    /**
     * 
     * @type {string}
     * @memberof LogsResponse
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof LogsResponse
     */
    'object': LogsResponseObjectEnum;
    /**
     * 
     * @type {number}
     * @memberof LogsResponse
     */
    'created_at': number;
    /**
     * 
     * @type {boolean}
     * @memberof LogsResponse
     */
    'livemode': boolean;
    /**
     * 
     * @type {string}
     * @memberof LogsResponse
     */
    'method': string;
    /**
     * 
     * @type {string}
     * @memberof LogsResponse
     */
    'url': string;
    /**
     * 
     * @type {string}
     * @memberof LogsResponse
     */
    'status': string;
    /**
     * 
     * @type {string}
     * @memberof LogsResponse
     */
    'version': string;
    /**
     * 
     * @type {string}
     * @memberof LogsResponse
     */
    'ip_address': string;
    /**
     * 
     * @type {string}
     * @memberof LogsResponse
     */
    'related': string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof LogsResponse
     */
    'query_string'?: { [key: string]: any; } | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof LogsResponse
     */
    'request_body'?: { [key: string]: any; } | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof LogsResponse
     */
    'response_body'?: { [key: string]: any; } | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof LogsResponse
     */
    'request_headers'?: { [key: string]: string; } | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof LogsResponse
     */
    'response_headers'?: { [key: string]: string; } | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof LogsResponse
     */
    'searchable_tags'?: Array<string>;
}

export const LogsResponseObjectEnum = {
    log: 'log'
} as const;

export type LogsResponseObjectEnum = typeof LogsResponseObjectEnum[keyof typeof LogsResponseObjectEnum];


