/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import {ChargeRequest} from './charge-request';
// May contain unused imports in some cases
// @ts-ignore
import {CustomerShippingContacts} from './customer-shipping-contacts';
// May contain unused imports in some cases
// @ts-ignore
import {OrderDiscountLinesRequest} from './order-discount-lines-request';
// May contain unused imports in some cases
// @ts-ignore
import {OrderTaxRequest} from './order-tax-request';
// May contain unused imports in some cases
// @ts-ignore
import {
  OrderUpdateFiscalEntityRequest
} from './order-update-fiscal-entity-request';
// May contain unused imports in some cases
// @ts-ignore
import {
  OrderUpdateRequestCustomerInfo
} from './order-update-request-customer-info';
// May contain unused imports in some cases
// @ts-ignore
import {Product} from './product';
// May contain unused imports in some cases
// @ts-ignore
import {ShippingRequest} from './shipping-request';

/**
 * Order update payload. Only supported fields can be modified.
 * @export
 * @interface OrderUpdateRequest
 */
export interface OrderUpdateRequest {
    /**
     * Currency code in ISO 4217 (3-letter uppercase).
     * @type {string}
     * @memberof OrderUpdateRequest
     */
    'currency'?: string;
    /**
     * 
     * @type {OrderUpdateRequestCustomerInfo}
     * @memberof OrderUpdateRequest
     */
    'customer_info'?: OrderUpdateRequestCustomerInfo;
    /**
     * List of [products](https://developers.femsa.com/v2.1.0/reference/orderscreateproduct) that are sold in the order. You must have at least one product.
     * @type {Array<Product>}
     * @memberof OrderUpdateRequest
     */
    'line_items'?: Array<Product>;
    /**
     * 
     * @type {Array<ChargeRequest>}
     * @memberof OrderUpdateRequest
     */
    'charges'?: Array<ChargeRequest>;
    /**
     * List of [discounts](https://developers.femsa.com/v2.1.0/reference/orderscreatediscountline) that are applied to the order. You must have at least one discount.
     * @type {Array<OrderDiscountLinesRequest>}
     * @memberof OrderUpdateRequest
     */
    'discount_lines'?: Array<OrderDiscountLinesRequest>;
    /**
     * 
     * @type {Array<OrderTaxRequest>}
     * @memberof OrderUpdateRequest
     */
    'tax_lines'?: Array<OrderTaxRequest>;
    /**
     * Existing shipping contact id from the customer to link to this order.
     * @type {string}
     * @memberof OrderUpdateRequest
     */
    'shipping_contact_id'?: string | null;
    /**
     * 
     * @type {CustomerShippingContacts}
     * @memberof OrderUpdateRequest
     */
    'shipping_contact'?: CustomerShippingContacts;
    /**
     * List of [shipping costs](https://developers.femsa.com/v2.1.0/reference/orderscreateshipping). If the online store offers digital products.
     * @type {Array<ShippingRequest>}
     * @memberof OrderUpdateRequest
     */
    'shipping_lines'?: Array<ShippingRequest>;
    /**
     * Existing fiscal entity id from the customer to link to this order.
     * @type {string}
     * @memberof OrderUpdateRequest
     */
    'fiscal_entity_id'?: string | null;
    /**
     * 
     * @type {OrderUpdateFiscalEntityRequest}
     * @memberof OrderUpdateRequest
     */
    'fiscal_entity'?: OrderUpdateFiscalEntityRequest;
    /**
     * URL where the customer should be redirected after completing a payment flow (if applicable).
     * @type {string}
     * @memberof OrderUpdateRequest
     */
    'return_url'?: string;
    /**
     * Arbitrary key-value data that you can attach to the order for your internal use. It is not used for payment processing. Keys should be strings; values can be any JSON value. 
     * @type {{ [key: string]: any; }}
     * @memberof OrderUpdateRequest
     */
    'metadata'?: { [key: string]: any; };
    /**
     * Order status update (only allowed transitions will be accepted).
     * @type {string}
     * @memberof OrderUpdateRequest
     */
    'status'?: string;
}

