/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CustomerShippingContactsResponse } from './customer-shipping-contacts-response';
// May contain unused imports in some cases
// @ts-ignore
import { CustomerShippingContactsResponseAddress } from './customer-shipping-contacts-response-address';

/**
 * @type OrderResponseShippingContact
 * Shipping contact associated with the order. It may be `null` when not provided/required.
 * @export
 */
export type OrderResponseShippingContact = CustomerShippingContactsResponse;


