/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import {ChargeRequest} from './charge-request';
// May contain unused imports in some cases
// @ts-ignore
import {CheckoutRequest} from './checkout-request';
// May contain unused imports in some cases
// @ts-ignore
import {CustomerShippingContacts} from './customer-shipping-contacts';
// May contain unused imports in some cases
// @ts-ignore
import {OrderDiscountLinesRequest} from './order-discount-lines-request';
// May contain unused imports in some cases
// @ts-ignore
import {OrderFiscalEntityRequest} from './order-fiscal-entity-request';
// May contain unused imports in some cases
// @ts-ignore
import {OrderRequestCustomerInfo} from './order-request-customer-info';
// May contain unused imports in some cases
// @ts-ignore
import {OrderTaxRequest} from './order-tax-request';
// May contain unused imports in some cases
// @ts-ignore
import {Product} from './product';
// May contain unused imports in some cases
// @ts-ignore
import {ShippingRequest} from './shipping-request';

/**
 * a order
 * @export
 * @interface OrderRequest
 */
export interface OrderRequest {
    /**
     * Currency with which the payment will be made.
     * @type {string}
     * @memberof OrderRequest
     */
    'currency': string;
    /**
     * 
     * @type {OrderRequestCustomerInfo}
     * @memberof OrderRequest
     */
    'customer_info': OrderRequestCustomerInfo;
    /**
     * List of [products](https://developers.digitalfemsa.io/reference/orderscreateproduct) that are sold in the order. You must have at least one product.
     * @type {Array<Product>}
     * @memberof OrderRequest
     */
    'line_items': Array<Product>;
    /**
     * List of [charges](https://developers.digitalfemsa.io/reference/orderscreatecharge) that are applied to the order
     * @type {Array<ChargeRequest>}
     * @memberof OrderRequest
     */
    'charges'?: Array<ChargeRequest>;
    /**
     * 
     * @type {CheckoutRequest}
     * @memberof OrderRequest
     */
    'checkout'?: CheckoutRequest;
    /**
     * List of [discounts](https://developers.digitalfemsa.io/reference/orderscreatediscountline) that are applied to the order. You must have at least one discount.
     * @type {Array<OrderDiscountLinesRequest>}
     * @memberof OrderRequest
     */
    'discount_lines'?: Array<OrderDiscountLinesRequest>;
    /**
     * List of [taxes](https://developers.digitalfemsa.io/reference/orderscreatetaxes) that are applied to the order.
     * @type {Array<OrderTaxRequest>}
     * @memberof OrderRequest
     */
    'tax_lines'?: Array<OrderTaxRequest>;
    /**
     * Allows you to fill out the shipping information at checkout
     * @type {boolean}
     * @memberof OrderRequest
     */
    'needs_shipping_contact'?: boolean;
    /**
     * 
     * @type {CustomerShippingContacts}
     * @memberof OrderRequest
     */
    'shipping_contact'?: CustomerShippingContacts;
    /**
     * List of [shipping costs](https://developers.digitalfemsa.io/reference/orderscreateshipping). If the online store offers digital products.
     * @type {Array<ShippingRequest>}
     * @memberof OrderRequest
     */
    'shipping_lines'?: Array<ShippingRequest>;
    /**
     * 
     * @type {OrderFiscalEntityRequest}
     * @memberof OrderRequest
     */
    'fiscal_entity'?: OrderFiscalEntityRequest;
    /**
     * Indicates the processing mode for the order, either ecommerce, recurrent or validation.
     * @type {string}
     * @memberof OrderRequest
     */
    'processing_mode'?: string;
    /**
     * Arbitrary key-value data that you can attach to the order for your internal use (e.g. `customer_segment`, `sales_channel`, `internal_order_id`). It is not used for payment processing or fraud decisions. Keys should be strings; values can be any JSON value.
     * @type {{ [key: string]: any; }}
     * @memberof OrderRequest
     */
    'metadata'?: { [key: string]: any; };
}

