/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import {OrderFiscalEntityResponse} from './order-fiscal-entity-response';
// May contain unused imports in some cases
// @ts-ignore
import {OrderResponseChannel} from './order-response-channel';
// May contain unused imports in some cases
// @ts-ignore
import {OrderResponseCharges} from './order-response-charges';
// May contain unused imports in some cases
// @ts-ignore
import {OrderResponseCheckout} from './order-response-checkout';
// May contain unused imports in some cases
// @ts-ignore
import {OrderResponseCustomerInfo} from './order-response-customer-info';
// May contain unused imports in some cases
// @ts-ignore
import {OrderResponseDiscountLines} from './order-response-discount-lines';
// May contain unused imports in some cases
// @ts-ignore
import {OrderResponseProducts} from './order-response-products';
// May contain unused imports in some cases
// @ts-ignore
import {OrderResponseShippingContact} from './order-response-shipping-contact';

/**
 * Order model. Some nested resources are returned as list previews (for example: `charges`, `line_items`), and may be `null` depending on the request/context. The `checkout` field is only present when the order is linked to a checkout (`channel.checkout_request_id`). 
 * @export
 * @interface OrderResponse
 */
export interface OrderResponse {
    /**
     * 
     * @type {string}
     * @memberof OrderResponse
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderResponse
     */
    'object'?: OrderResponseObjectEnum;
    /**
     * 
     * @type {boolean}
     * @memberof OrderResponse
     */
    'livemode'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof OrderResponse
     */
    'amount'?: number;
    /**
     * 
     * @type {string}
     * @memberof OrderResponse
     */
    'currency'?: string;
    /**
     * Current payment status of the order. It can be `null` for orders without payment information yet.
     * @type {string}
     * @memberof OrderResponse
     */
    'payment_status'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof OrderResponse
     */
    'amount_refunded'?: number;
    /**
     * Indicates whether the order uses split payments (when available/configured).
     * @type {boolean}
     * @memberof OrderResponse
     */
    'split_payment'?: boolean | null;
    /**
     * Metadata attached to the order.
     * @type {{ [key: string]: any; }}
     * @memberof OrderResponse
     */
    'metadata'?: { [key: string]: any; };
    /**
     * Indicates whether the order is currently refundable.
     * @type {boolean}
     * @memberof OrderResponse
     */
    'is_refundable'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof OrderResponse
     */
    'created_at'?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderResponse
     */
    'updated_at'?: number;
    /**
     * 
     * @type {OrderResponseCustomerInfo}
     * @memberof OrderResponse
     */
    'customer_info'?: OrderResponseCustomerInfo;
    /**
     * 
     * @type {OrderResponseShippingContact}
     * @memberof OrderResponse
     */
    'shipping_contact'?: OrderResponseShippingContact | null;
    /**
     * 
     * @type {OrderResponseChannel}
     * @memberof OrderResponse
     */
    'channel'?: OrderResponseChannel | null;
    /**
     * 
     * @type {OrderFiscalEntityResponse}
     * @memberof OrderResponse
     */
    'fiscal_entity'?: OrderFiscalEntityResponse | null;
    /**
     * 
     * @type {OrderResponseCheckout}
     * @memberof OrderResponse
     */
    'checkout'?: OrderResponseCheckout;
    /**
     * 
     * @type {OrderResponseProducts}
     * @memberof OrderResponse
     */
    'line_items'?: OrderResponseProducts;
    /**
     * 
     * @type {OrderResponseDiscountLines}
     * @memberof OrderResponse
     */
    'discount_lines'?: OrderResponseDiscountLines;
    /**
     * 
     * @type {OrderResponseCharges}
     * @memberof OrderResponse
     */
    'charges'?: OrderResponseCharges;
    /**
     * Partial reference information (when applicable). Structure may vary depending on the payment flow.
     * @type {{ [key: string]: any; }}
     * @memberof OrderResponse
     */
    'partial_reference'?: { [key: string]: any; } | null;
    /**
     * Additional payment information (when available). Structure may vary.
     * @type {{ [key: string]: any; }}
     * @memberof OrderResponse
     */
    'payments_info'?: { [key: string]: any; } | null;
}

export const OrderResponseObjectEnum = {
    order: 'order'
} as const;

export type OrderResponseObjectEnum = typeof OrderResponseObjectEnum[keyof typeof OrderResponseObjectEnum];


