/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ChargeRequest } from './charge-request';
// May contain unused imports in some cases
// @ts-ignore
import { CustomerInfo } from './customer-info';
// May contain unused imports in some cases
// @ts-ignore
import { CustomerShippingContacts } from './customer-shipping-contacts';
// May contain unused imports in some cases
// @ts-ignore
import { OrderDiscountLinesRequest } from './order-discount-lines-request';
// May contain unused imports in some cases
// @ts-ignore
import { OrderTaxRequest } from './order-tax-request';
// May contain unused imports in some cases
// @ts-ignore
import { OrderUpdateFiscalEntityRequest } from './order-update-fiscal-entity-request';
// May contain unused imports in some cases
// @ts-ignore
import { Product } from './product';
// May contain unused imports in some cases
// @ts-ignore
import { ShippingRequest } from './shipping-request';

/**
 * Order update payload. Only supported fields can be modified.
 * @export
 * @interface OrderUpdateRequest
 */
export interface OrderUpdateRequest {
    /**
     * Order status update. Allowed values depend on server-side validations.
     * @type {string}
     * @memberof OrderUpdateRequest
     */
    'status'?: string;
    /**
     * Currency used for the order. Uses ISO 4217 (3-letter code). Allowed values depend on server-side validations.
     * @type {string}
     * @memberof OrderUpdateRequest
     */
    'currency'?: string;
    /**
     * 
     * @type {CustomerInfo}
     * @memberof OrderUpdateRequest
     */
    'customer_info'?: CustomerInfo;
    /**
     * List of products sold in the order.
     * @type {Array<Product>}
     * @memberof OrderUpdateRequest
     */
    'line_items'?: Array<Product>;
    /**
     * List of shipping costs applied to the order.
     * @type {Array<ShippingRequest>}
     * @memberof OrderUpdateRequest
     */
    'shipping_lines'?: Array<ShippingRequest>;
    /**
     * 
     * @type {Array<OrderTaxRequest>}
     * @memberof OrderUpdateRequest
     */
    'tax_lines'?: Array<OrderTaxRequest>;
    /**
     * List of discounts applied to the order.
     * @type {Array<OrderDiscountLinesRequest>}
     * @memberof OrderUpdateRequest
     */
    'discount_lines'?: Array<OrderDiscountLinesRequest>;
    /**
     * Additional information attached to the order.
     * @type {{ [key: string]: any; }}
     * @memberof OrderUpdateRequest
     */
    'metadata'?: { [key: string]: any; };
    /**
     * URL to redirect the customer after completing the flow (when applicable).
     * @type {string}
     * @memberof OrderUpdateRequest
     */
    'return_url'?: string;
    /**
     * Add new charges to the order. Subject to server-side validations (for example, maximum charges rules). 
     * @type {Array<ChargeRequest>}
     * @memberof OrderUpdateRequest
     */
    'charges'?: Array<ChargeRequest>;
    /**
     * References an existing customer shipping contact.
     * @type {string}
     * @memberof OrderUpdateRequest
     */
    'shipping_contact_id'?: string | null;
    /**
     * 
     * @type {CustomerShippingContacts}
     * @memberof OrderUpdateRequest
     */
    'shipping_contact'?: CustomerShippingContacts;
    /**
     * References an existing customer fiscal entity.
     * @type {string}
     * @memberof OrderUpdateRequest
     */
    'fiscal_entity_id'?: string | null;
    /**
     * 
     * @type {OrderUpdateFiscalEntityRequest}
     * @memberof OrderUpdateRequest
     */
    'fiscal_entity'?: OrderUpdateFiscalEntityRequest;
}

