/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Channel information for the order (for example Checkout-related metadata). It may be `null`.
 * @export
 * @interface OrderResponseChannel
 */
export interface OrderResponseChannel {
    /**
     * 
     * @type {string}
     * @memberof OrderResponseChannel
     */
    'segment'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderResponseChannel
     */
    'checkout_request_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderResponseChannel
     */
    'checkout_request_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderResponseChannel
     */
    'id'?: string;
}

