/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import {FiscalEntityAddress} from './fiscal-entity-address';

/**
 * Fiscal entity of the order, Currently it is a purely informative field
 * @export
 * @interface OrderUpdateFiscalEntityRequest
 */
export interface OrderUpdateFiscalEntityRequest {
    /**
     * 
     * @type {FiscalEntityAddress}
     * @memberof OrderUpdateFiscalEntityRequest
     */
    'address': FiscalEntityAddress;
    /**
     * Email of the fiscal entity
     * @type {string}
     * @memberof OrderUpdateFiscalEntityRequest
     */
    'email'?: string;
    /**
     * Name of the fiscal entity
     * @type {string}
     * @memberof OrderUpdateFiscalEntityRequest
     */
    'name'?: string | null;
    /**
     * Arbitrary key-value data associated with the fiscal entity for your internal use. Keys should be strings; values can be any JSON value. 
     * @type {{ [key: string]: any; }}
     * @memberof OrderUpdateFiscalEntityRequest
     */
    'metadata'?: { [key: string]: any; };
    /**
     * Phone of the fiscal entity
     * @type {string}
     * @memberof OrderUpdateFiscalEntityRequest
     */
    'phone'?: string;
    /**
     * Tax ID of the fiscal entity
     * @type {string}
     * @memberof OrderUpdateFiscalEntityRequest
     */
    'tax_id'?: string | null;
}

