/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ChargeRequest } from './charge-request';
// May contain unused imports in some cases
// @ts-ignore
import { CheckoutRequest } from './checkout-request';
// May contain unused imports in some cases
// @ts-ignore
import { CustomerInfo } from './customer-info';
// May contain unused imports in some cases
// @ts-ignore
import { CustomerShippingContacts } from './customer-shipping-contacts';
// May contain unused imports in some cases
// @ts-ignore
import { FiscalEntityAddress } from './fiscal-entity-address';
// May contain unused imports in some cases
// @ts-ignore
import { OrderDiscountLinesRequest } from './order-discount-lines-request';
// May contain unused imports in some cases
// @ts-ignore
import { OrderTaxRequest } from './order-tax-request';
// May contain unused imports in some cases
// @ts-ignore
import { Product } from './product';
// May contain unused imports in some cases
// @ts-ignore
import { ShippingRequest } from './shipping-request';

/**
 * a order
 * @export
 * @interface OrderRequest
 */
export interface OrderRequest {
    /**
     * List of [charges](https://developers.digitalfemsa.io/reference/orderscreatecharge) that are applied to the order
     * @type {Array<ChargeRequest>}
     * @memberof OrderRequest
     */
    'charges'?: Array<ChargeRequest>;
    /**
     * 
     * @type {CheckoutRequest}
     * @memberof OrderRequest
     */
    'checkout'?: CheckoutRequest;
    /**
     * Optional return URL used by some payment/checkout flows.
     * @type {string}
     * @memberof OrderRequest
     */
    'return_url'?: string | null;
    /**
     * Currency with which the payment will be made. It uses the 3-letter code of the [International Standard ISO 4217.](https://es.wikipedia.org/wiki/ISO_4217)
     * @type {string}
     * @memberof OrderRequest
     */
    'currency': string;
    /**
     * 
     * @type {CustomerInfo}
     * @memberof OrderRequest
     */
    'customer_info': CustomerInfo;
    /**
     * List of [discounts](https://developers.digitalfemsa.io/reference/orderscreatediscountline) that are applied to the order. You must have at least one discount.
     * @type {Array<OrderDiscountLinesRequest>}
     * @memberof OrderRequest
     */
    'discount_lines'?: Array<OrderDiscountLinesRequest>;
    /**
     * Fiscal entity of the order, Currently it is a purely informative field
     * @type {object}
     * @memberof OrderRequest
     */
    'fiscal_entity'?: object;
    /**
     * List of [products](https://developers.digitalfemsa.io/reference/orderscreateproduct) that are sold in the order. You must have at least one product.
     * @type {Array<Product>}
     * @memberof OrderRequest
     */
    'line_items': Array<Product>;
    /**
     * Metadata associated with the order
     * @type {{ [key: string]: any; }}
     * @memberof OrderRequest
     */
    'metadata'?: { [key: string]: any; };
    /**
     * Allows you to fill out the shipping information at checkout
     * @type {boolean}
     * @memberof OrderRequest
     */
    'needs_shipping_contact'?: boolean;
    /**
     * Indicates the processing mode for the order, either ecommerce, recurrent or validation.
     * @type {string}
     * @memberof OrderRequest
     */
    'processing_mode'?: string;
    /**
     * 
     * @type {CustomerShippingContacts}
     * @memberof OrderRequest
     */
    'shipping_contact'?: CustomerShippingContacts;
    /**
     * List of [shipping costs](https://developers.digitalfemsa.io/reference/orderscreateshipping). If the online store offers digital products.
     * @type {Array<ShippingRequest>}
     * @memberof OrderRequest
     */
    'shipping_lines'?: Array<ShippingRequest>;
    /**
     * List of [taxes](https://developers.digitalfemsa.io/reference/orderscreatetaxes) that are applied to the order.
     * @type {Array<OrderTaxRequest>}
     * @memberof OrderRequest
     */
    'tax_lines'?: Array<OrderTaxRequest>;
}

