/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import {ChargesDataResponse} from './charges-data-response';
// May contain unused imports in some cases
// @ts-ignore
import {Pagination} from './pagination';

/**
 * @type OrderResponseCharges
 * List preview of charges created for the order. Charges are only created when included in the request or created later through payment flows. This field can be `null` depending on the response context. 
 * @export
 */
export type OrderResponseCharges = Pagination;


