/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Product
 */
export interface Product {
    /**
     * The name of the item. It will be displayed in the order.
     * @type {string}
     * @memberof Product
     */
    'name': string;
    /**
     * The price of the item in cents.
     * @type {number}
     * @memberof Product
     */
    'unit_price': number;
    /**
     * The quantity of the item in the order.
     * @type {number}
     * @memberof Product
     */
    'quantity': number;
    /**
     * The stock keeping unit for the item. It is used to identify the item in the order.
     * @type {string}
     * @memberof Product
     */
    'sku'?: string;
    /**
     * The brand of the item.
     * @type {string}
     * @memberof Product
     */
    'brand'?: string;
    /**
     * Short description of the item
     * @type {string}
     * @memberof Product
     */
    'description'?: string;
    /**
     * List of tags for the item. It is used to identify the item in the order.
     * @type {Array<string>}
     * @memberof Product
     */
    'tags'?: Array<string>;
    /**
     * Arbitrary key-value data for your internal use. Keys should be strings; values can be any JSON value. 
     * @type {{ [key: string]: any; }}
     * @memberof Product
     */
    'metadata'?: { [key: string]: any; };
}

