/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Shipping line request payload.
 * @export
 * @interface ShippingRequest
 */
export interface ShippingRequest {
    /**
     * Shipping amount in cents
     * @type {number}
     * @memberof ShippingRequest
     */
    'amount': number;
    /**
     * Carrier name for the shipment
     * @type {string}
     * @memberof ShippingRequest
     */
    'carrier'?: string;
    /**
     * Tracking number can be used to track the shipment
     * @type {string}
     * @memberof ShippingRequest
     */
    'tracking_number'?: string;
    /**
     * Method of shipment
     * @type {string}
     * @memberof ShippingRequest
     */
    'method'?: string;
    /**
     * Shipping line description
     * @type {string}
     * @memberof ShippingRequest
     */
    'description'?: string;
    /**
     * Hash where the user can send additional information for each \'shipping\'.
     * @type {{ [key: string]: any; }}
     * @memberof ShippingRequest
     */
    'metadata'?: { [key: string]: any; };
}

