/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Destination payout method used to make the transfer.
 * @export
 * @interface TransfersResponseDestination
 */
export interface TransfersResponseDestination {
    /**
     * Unique identifier of the payee.
     * @type {string}
     * @memberof TransfersResponseDestination
     */
    'payee_id': string;
    /**
     * Unique identifier of the payout method.
     * @type {string}
     * @memberof TransfersResponseDestination
     */
    'id': string;
    /**
     * Date and time of creation of the payout method in Unix format.
     * @type {number}
     * @memberof TransfersResponseDestination
     */
    'created_at': number;
    /**
     * Object name, present for bank transfer destination.
     * @type {string}
     * @memberof TransfersResponseDestination
     */
    'object'?: string | null;
    /**
     * Destination type.
     * @type {string}
     * @memberof TransfersResponseDestination
     */
    'type'?: string | null;
    /**
     * Last 4 digits of the destination account number.
     * @type {string}
     * @memberof TransfersResponseDestination
     */
    'last4'?: string | null;
    /**
     * Name of the account holder.
     * @type {string}
     * @memberof TransfersResponseDestination
     */
    'account_holder_name'?: string | null;
    /**
     * Name of the bank.
     * @type {string}
     * @memberof TransfersResponseDestination
     */
    'bank'?: string | null;
}

