/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Transaction object.
 * @export
 * @interface TransactionResponse
 */
export interface TransactionResponse {
    /**
     * Unique identifier of the transaction.
     * @type {string}
     * @memberof TransactionResponse
     */
    'id': string;
    /**
     * Object name, which is transaction.
     * @type {string}
     * @memberof TransactionResponse
     */
    'object': string;
    /**
     * The amount of the transaction.
     * @type {number}
     * @memberof TransactionResponse
     */
    'amount': number;
    /**
     * The amount to be deducted for taxes and commissions.
     * @type {number}
     * @memberof TransactionResponse
     */
    'fee': number;
    /**
     * The net amount after deducting commissions and taxes.
     * @type {number}
     * @memberof TransactionResponse
     */
    'net': number;
    /**
     * The currency of the transaction. It uses the 3-letter code of ISO 4217.
     * @type {string}
     * @memberof TransactionResponse
     */
    'currency': string;
    /**
     * Code indicating transaction status.
     * @type {string}
     * @memberof TransactionResponse
     */
    'status': TransactionResponseStatusEnum;
    /**
     * Transaction type.
     * @type {string}
     * @memberof TransactionResponse
     */
    'type': TransactionResponseTypeEnum;
    /**
     * Date and time of creation of the transaction in Unix format.
     * @type {number}
     * @memberof TransactionResponse
     */
    'created_at': number;
    /**
     * Indicates whether the transaction was created in live mode or test mode.
     * @type {boolean}
     * @memberof TransactionResponse
     */
    'livemode': boolean;
    /**
     * Charge ID associated with the transaction (present only if the transaction belongs to a charge).
     * @type {string}
     * @memberof TransactionResponse
     */
    'charge'?: string | null;
    /**
     * Transfer ID associated with the transaction (present only if the transaction belongs to a transfer).
     * @type {string}
     * @memberof TransactionResponse
     */
    'transfer'?: string | null;
    /**
     * Date and time when the transaction was transferred, in Unix format.
     * @type {number}
     * @memberof TransactionResponse
     */
    'transferred_at'?: number | null;
    /**
     * Transaction fee formula identifier (if available).
     * @type {string}
     * @memberof TransactionResponse
     */
    'formula'?: string | null;
}

export const TransactionResponseStatusEnum = {
    unprocessed: 'unprocessed',
    pending: 'pending',
    available: 'available',
    owing: 'owing',
    paidOut: 'paid_out',
    onHold: 'on_hold',
    retained: 'retained',
    voided: 'voided'
} as const;

export type TransactionResponseStatusEnum = typeof TransactionResponseStatusEnum[keyof typeof TransactionResponseStatusEnum];
export const TransactionResponseTypeEnum = {
    capture: 'capture',
    captureReversal: 'capture_reversal',
    liquidation: 'liquidation',
    liquidationReversal: 'liquidation_reversal',
    payout: 'payout',
    payoutReversal: 'payout_reversal',
    refund: 'refund',
    refundReversal: 'refund_reversal',
    roundingAdjustment: 'rounding_adjustment',
    transfer: 'transfer',
    transferred: 'transferred',
    retention: 'retention',
    temporaryRetention: 'temporary_retention',
    cashoutRetention: 'cashout_retention',
    cashoutConfirmation: 'cashout_confirmation',
    cashoutCancelation: 'cashout_cancelation',
    autofundCapture: 'autofund_capture'
} as const;

export type TransactionResponseTypeEnum = typeof TransactionResponseTypeEnum[keyof typeof TransactionResponseTypeEnum];


