/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TransfersResponseDestination } from './transfers-response-destination';

/**
 * A transfer represents the action of sending an amount to a business bank account including the status, amount and destination used to make the transfer.
 * @export
 * @interface TransfersResponse
 */
export interface TransfersResponse {
    /**
     * Unique identifier of the transfer.
     * @type {string}
     * @memberof TransfersResponse
     */
    'id': string;
    /**
     * Object name, which is transfer.
     * @type {string}
     * @memberof TransfersResponse
     */
    'object': string;
    /**
     * Amount in cents of the transfer.
     * @type {number}
     * @memberof TransfersResponse
     */
    'amount': number;
    /**
     * Date and time of creation of the transfer in Unix format.
     * @type {number}
     * @memberof TransfersResponse
     */
    'created_at': number;
    /**
     * The currency of the transfer. It uses the 3-letter code of ISO 4217.
     * @type {string}
     * @memberof TransfersResponse
     */
    'currency': string;
    /**
     * Indicates whether the transfer was created in live mode or test mode.
     * @type {boolean}
     * @memberof TransfersResponse
     */
    'livemode': boolean;
    /**
     * Code indicating transfer status.
     * @type {string}
     * @memberof TransfersResponse
     */
    'status': string;
    /**
     * Reference number of the transfer.
     * @type {string}
     * @memberof TransfersResponse
     */
    'statement_reference': string;
    /**
     * Description of the transfer.
     * @type {string}
     * @memberof TransfersResponse
     */
    'statement_description': string;
    /**
     * 
     * @type {TransfersResponseDestination}
     * @memberof TransfersResponse
     */
    'destination': TransfersResponseDestination;
    /**
     * Total fee for the transfer (present only when requesting the \'details\' expansion).
     * @type {number}
     * @memberof TransfersResponse
     */
    'fee'?: number | null;
    /**
     * Present only when requesting the \'details\' expansion.
     * @type {number}
     * @memberof TransfersResponse
     */
    'capture_amount'?: number | null;
    /**
     * Present only when requesting the \'details\' expansion.
     * @type {number}
     * @memberof TransfersResponse
     */
    'capture_fee'?: number | null;
    /**
     * Present only when requesting the \'details\' expansion.
     * @type {number}
     * @memberof TransfersResponse
     */
    'capture_net'?: number | null;
    /**
     * Present only when requesting the \'details\' expansion.
     * @type {number}
     * @memberof TransfersResponse
     */
    'refund_amount'?: number | null;
    /**
     * Present only when requesting the \'details\' expansion.
     * @type {number}
     * @memberof TransfersResponse
     */
    'refund_fee'?: number | null;
    /**
     * Present only when requesting the \'details\' expansion.
     * @type {number}
     * @memberof TransfersResponse
     */
    'refund_net'?: number | null;
    /**
     * Present only when requesting the \'details\' expansion.
     * @type {number}
     * @memberof TransfersResponse
     */
    'payout_amount'?: number | null;
    /**
     * Present only when requesting the \'details\' expansion.
     * @type {number}
     * @memberof TransfersResponse
     */
    'payout_fee'?: number | null;
    /**
     * Present only when requesting the \'details\' expansion.
     * @type {number}
     * @memberof TransfersResponse
     */
    'payout_net'?: number | null;
    /**
     * Present only when requesting the \'details\' expansion.
     * @type {Array<object>}
     * @memberof TransfersResponse
     */
    'transactions'?: Array<object> | null;
}

