/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UpdatePaymentMethodsAmount } from './update-payment-methods-amount';
// May contain unused imports in some cases
// @ts-ignore
import { UpdatePaymentMethodsExpiresAt } from './update-payment-methods-expires-at';

/**
 * 
 * @export
 * @interface UpdatePaymentMethods
 */
export interface UpdatePaymentMethods {
    /**
     * 
     * @type {UpdatePaymentMethodsExpiresAt}
     * @memberof UpdatePaymentMethods
     */
    'expires_at'?: UpdatePaymentMethodsExpiresAt;
    /**
     * 
     * @type {UpdatePaymentMethodsAmount}
     * @memberof UpdatePaymentMethods
     */
    'amount'?: UpdatePaymentMethodsAmount;
    /**
     * 
     * @type {string}
     * @memberof UpdatePaymentMethods
     */
    'type'?: string;
}

