/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * List of discounts that apply to the order.
 * @export
 * @interface UpdateOrderDiscountLinesRequest
 */
export interface UpdateOrderDiscountLinesRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdateOrderDiscountLinesRequest
     */
    'amount'?: number;
    /**
     * Discount code.
     * @type {string}
     * @memberof UpdateOrderDiscountLinesRequest
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateOrderDiscountLinesRequest
     */
    'type'?: UpdateOrderDiscountLinesRequestTypeEnum;
}

export const UpdateOrderDiscountLinesRequestTypeEnum = {
    loyalty: 'loyalty',
    campaign: 'campaign',
    coupon: 'coupon',
    sign: 'sign'
} as const;

export type UpdateOrderDiscountLinesRequestTypeEnum = typeof UpdateOrderDiscountLinesRequestTypeEnum[keyof typeof UpdateOrderDiscountLinesRequestTypeEnum];


