/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Create a new tax line for an existing order.
 * @export
 * @interface UpdateOrderTaxRequest
 */
export interface UpdateOrderTaxRequest {
    /**
     * The amount to be collected for tax in cents
     * @type {number}
     * @memberof UpdateOrderTaxRequest
     */
    'amount': number;
    /**
     * Description or tax name
     * @type {string}
     * @memberof UpdateOrderTaxRequest
     */
    'description': string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof UpdateOrderTaxRequest
     */
    'metadata'?: { [key: string]: any; };
}

