/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import {
  CustomerPaymentMethodsRequest
} from './customer-payment-methods-request';

/**
 * Request body to update a customer.
 * @export
 * @interface UpdateCustomer
 */
export interface UpdateCustomer {
    /**
     * Customer\'s name.
     * @type {string}
     * @memberof UpdateCustomer
     */
    'name'?: string;
    /**
     * Customer email address.
     * @type {string}
     * @memberof UpdateCustomer
     */
    'email'?: string;
    /**
     * Customer phone number.
     * @type {string}
     * @memberof UpdateCustomer
     */
    'phone'?: string;
    /**
     * True if the customer represents a company.
     * @type {boolean}
     * @memberof UpdateCustomer
     */
    'corporate'?: boolean;
    /**
     * Merchant-defined reference used to identify the customer in your system.
     * @type {string}
     * @memberof UpdateCustomer
     */
    'custom_reference'?: string;
    /**
     * Arbitrary metadata associated with the customer.
     * @type {{ [key: string]: any; }}
     * @memberof UpdateCustomer
     */
    'metadata'?: { [key: string]: any; };
    /**
     * Customer payment sources to create/attach (offline recurrent references).
     * @type {Array<CustomerPaymentMethodsRequest>}
     * @memberof UpdateCustomer
     */
    'payment_sources'?: Array<CustomerPaymentMethodsRequest>;
    /**
     * Sets the default payment source for the customer (must be an existing payment source on the customer).
     * @type {string}
     * @memberof UpdateCustomer
     */
    'default_payment_source_id'?: string;
    /**
     * Sets the default fiscal entity for the customer (must be an existing fiscal entity on the customer).
     * @type {string}
     * @memberof UpdateCustomer
     */
    'default_fiscal_entity_id'?: string;
    /**
     * Sets the default shipping contact for the customer (must be an existing shipping contact on the customer).
     * @type {string}
     * @memberof UpdateCustomer
     */
    'default_shipping_contact_id'?: string;
}

