/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Parameters used to update a webhook. All fields are optional; send only the fields you want to change.
 * @export
 * @interface WebhookUpdateRequest
 */
export interface WebhookUpdateRequest {
    /**
     * Webhook endpoint URL. Local URLs are not allowed.
     * @type {string}
     * @memberof WebhookUpdateRequest
     */
    'url'?: string;
    /**
     * List of event types the webhook is subscribed to.
     * @type {Array<string>}
     * @memberof WebhookUpdateRequest
     */
    'subscribed_events'?: Array<string>;
    /**
     * Alias for subscribed_events.
     * @type {Array<string>}
     * @memberof WebhookUpdateRequest
     * @deprecated
     */
    'events'?: Array<string>;
    /**
     * Indicates whether the webhook uses synchronous delivery behavior.
     * @type {boolean}
     * @memberof WebhookUpdateRequest
     */
    'synchronous'?: boolean;
    /**
     * Activates or deactivates the webhook.
     * @type {boolean}
     * @memberof WebhookUpdateRequest
     */
    'active'?: boolean;
    /**
     * Optional description of the webhook.
     * @type {string}
     * @memberof WebhookUpdateRequest
     */
    'description'?: string | null;
}

