/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Represents a webhook endpoint configured to receive event notifications.
 * @export
 * @interface WebhookResponse
 */
export interface WebhookResponse {
    /**
     * Unique identifier of the webhook.
     * @type {string}
     * @memberof WebhookResponse
     */
    'id': string;
    /**
     * Object name, which is webhook.
     * @type {string}
     * @memberof WebhookResponse
     */
    'object': string;
    /**
     * The URL where events will be delivered.
     * @type {string}
     * @memberof WebhookResponse
     */
    'url': string;
    /**
     * Current delivery status of the webhook.
     * @type {string}
     * @memberof WebhookResponse
     */
    'status': WebhookResponseStatusEnum;
    /**
     * List of event types the webhook is subscribed to.
     * @type {Array<string>}
     * @memberof WebhookResponse
     */
    'subscribed_events': Array<string>;
    /**
     * Indicates whether the webhook uses synchronous delivery behavior.
     * @type {boolean}
     * @memberof WebhookResponse
     */
    'synchronous': boolean;
    /**
     * Optional description of the webhook.
     * @type {string}
     * @memberof WebhookResponse
     */
    'description'?: string | null;
    /**
     * Indicates whether the webhook is in live mode or test mode.
     * @type {boolean}
     * @memberof WebhookResponse
     */
    'livemode': boolean;
    /**
     * Indicates whether the webhook is active.
     * @type {boolean}
     * @memberof WebhookResponse
     */
    'active': boolean;
}

export const WebhookResponseStatusEnum = {
    beingPinged: 'being_pinged',
    listening: 'listening',
    intermittentErrors: 'intermittent_errors',
    unresponsive: 'unresponsive',
    error: 'error',
    disabled: 'disabled'
} as const;

export type WebhookResponseStatusEnum = typeof WebhookResponseStatusEnum[keyof typeof WebhookResponseStatusEnum];


