/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WebhookLog
 */
export interface WebhookLog {
    /**
     * 
     * @type {number}
     * @memberof WebhookLog
     */
    'failed_attempts': number;
    /**
     * 
     * @type {string}
     * @memberof WebhookLog
     */
    'id': string;
    /**
     * 
     * @type {number}
     * @memberof WebhookLog
     */
    'last_attempted_at': number;
    /**
     * 
     * @type {number}
     * @memberof WebhookLog
     */
    'last_http_response_status': number;
    /**
     * 
     * @type {string}
     * @memberof WebhookLog
     */
    'object'?: WebhookLogObjectEnum;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof WebhookLog
     */
    'response_data'?: { [key: string]: any; } | null;
    /**
     * 
     * @type {string}
     * @memberof WebhookLog
     */
    'url': string;
}

export const WebhookLogObjectEnum = {
    webhookLog: 'webhook_log'
} as const;

export type WebhookLogObjectEnum = typeof WebhookLogObjectEnum[keyof typeof WebhookLogObjectEnum];


