/* tslint:disable */
/* eslint-disable */
/**
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Represents a webhook signing key after it has been deleted.
 * @export
 * @interface WebhookKeyDeleteResponse
 */
export interface WebhookKeyDeleteResponse {
    /**
     * Unique identifier of the webhook key
     * @type {string}
     * @memberof WebhookKeyDeleteResponse
     */
    'id': string;
    /**
     * Object name, value is webhook_key
     * @type {string}
     * @memberof WebhookKeyDeleteResponse
     */
    'object': string;
    /**
     * Indicates if the webhook key is active
     * @type {boolean}
     * @memberof WebhookKeyDeleteResponse
     */
    'active': boolean;
    /**
     * Indicates if the webhook key is in live mode
     * @type {boolean}
     * @memberof WebhookKeyDeleteResponse
     */
    'livemode': boolean;
    /**
     * Unix timestamp in seconds with the creation date of the webhook key
     * @type {number}
     * @memberof WebhookKeyDeleteResponse
     */
    'created_at': number;
    /**
     * Unix timestamp in seconds when the webhook key was deactivated (if applicable).
     * @type {number}
     * @memberof WebhookKeyDeleteResponse
     */
    'deactivated_at'?: number | null;
    /**
     * Indicates if the webhook key is deleted
     * @type {boolean}
     * @memberof WebhookKeyDeleteResponse
     */
    'deleted': boolean;
}

